module.exports = [{"id":81420,"deepfryd_id":"29500-2264","features":"Play music throughout your home easily and wirelessly","question":"What is needed to set up my SoundTouch speaker?","answer":"All you need is a home Wi-Fi network and a smartphone or tablet. Everything else required is included in the box."},
{"id":81420,"deepfryd_id":"68382-181","features":"Proprietary acoustic design delivers big performance from a compact speaker","question":"What Internet streaming music can I play?","answer":"SoundTouch speakers let you play Internet music services like Spotify®, Pandora®, iHeartRadio™, Deezer, TuneIn, Sirius, and Amazon Music. (where available)"},
{"id":81420,"deepfryd_id":"63629-4151","features":"Works with your home Wi-Fi network and Bluetooth® devices so you can play almost anything you can imagine","question":"Can SoundTouch speakers be used in a public Wi-Fi® spot (airports, coffee shops, etc.)?","answer":"No. Although most of these networks are free to use, their sign-up/sign-in processes differ from the SoundTouch app setup process. SoundTouch products are designed for in-home use, not on the go."},
{"id":81420,"deepfryd_id":"50436-0919","features":"Add SoundTouch® systems to play the same music throughout, or different music in different rooms","question":"Can I play music stored on my computer?","answer":"Yes. SoundTouch speakers can play music stored on your computer that is managed by iTunes or Windows Media Player."},
{"id":81420,"deepfryd_id":"46994-235","features":"Powerful app transforms your phone into your music remote control","question":"How many speakers can I have on my network at one time?","answer":"It depends on the bandwidth of your home Wi-Fi network. For most homes, we expect you can have up to four speakers connected wirelessly. For more than four rooms, we recommend using Ethernet wired connections to some of them."},
{"id":81420,"deepfryd_id":"0093-7147","features":"Press one of six presets on the speaker, remote or app to play your favorite music","question":"Can I stream different music to different rooms?","answer":"Yes, if you have multiple SoundTouch products, you can stream different music in different rooms, the same music in every room or customize zones to play what you want where you want."},
{"id":81420,"deepfryd_id":"0078-0635","features":"strategy","question":"What operating systems are compatible with the SoundTouch app?","answer":"The app is compatible with Windows® 7, 8, 10; 64-bit Macs running OS X 10.8 and later; any iPhone, iPad or iPod touch running iOS 8.2 and later; Android devices running Android 4.4 and later."},
{"id":81420,"deepfryd_id":"21220-119","features":"initiative","question":"Can I play stored music from an NAS (Network Attached Storage) drive on SoundTouch speakers?","answer":"Yes, SoundTouch speakers are compatible with select NAS drives, including Synology’s DiskStation, Passport + and Western Digital’s My Cloud™, so you can stream your personal music library even while your computer is off."},
{"id":81420,"deepfryd_id":"54868-5077","features":"workforce","question":"Can SoundTouch speakers stream AM/FM radio or TV audio from one room to another?","answer":"Yes. SoundTouch speakers can stream Internet radio stations through a TuneIn app integration."},
{"id":81420,"deepfryd_id":"43269-711","features":"artificial intelligence","question":"Does the speaker support Bluetooth?","answer":"Yes. Users can wirelessly stream music from a Bluetooth device to listen to even more sources, such as YouTube."},
{"id":81420,"deepfryd_id":"54312-325","features":"collaboration","question":"Can I stream music from multiple computers using SoundTouch speakers?","answer":"Yes, as long as each computer has the SoundTouch app installed on it. Each computer appears as a separate library on the app’s source list."},
{"id":81420,"deepfryd_id":"36987-1343","features":"strategy","question":"Does the speaker have a battery?","answer":"No, it does not have a battery."},
{"id":81420,"deepfryd_id":"59667-0021","features":"human-resource","question":"Do the speakers support near-field communications?","answer":"No. SoundTouch speakers support Bluetooth connectivity pairing via the physical buttons on the speaker or the controller app."},
{"id":81420,"deepfryd_id":"54868-2126","features":"Digitized","question":"Does the speaker support AirPlay?","answer":"No. Current speakers no longer support AirPlay. However, previous generation SoundTouch 20 and 30 speakers will continue to support it."},
{"id":81420,"deepfryd_id":"37000-076","features":"human-resource","question":"Can SoundTouch speakers be used together?","answer":"Yes. Any one of these speakers can be used with another system (from the current series or from a previous series) to create a multi-room audio system."},
{"id":81420,"deepfryd_id":"68428-158","features":"even-keeled","question":"What can I do with the Bose Skill?","answer":"With Bose Skill, you can play music on your SoundTouch speakers by talking to any Alexa-enabled device like an Amazon Echo Dot."},
{"id":81420,"deepfryd_id":"10237-831","features":"De-engineered","question":"Which SoundTouch products are compatible with the Bose Skill?","answer":"The Bose Skill is compatible with all current generation SoundTouch speakers and previous SoundTouch speakers/systems that support Bluetooth connectivity."},
{"id":81420,"deepfryd_id":"61957-9403","features":"encompassing","question":"What music services work with the Bose Skill and SoundTouch?","answer":"The music services that currently work with Bose Skill are Amazon Music, Pandora, TuneIn, SiriusXM, and iHeartRadio."},
{"id":81420,"deepfryd_id":"17089-359","features":"throughput","question":"Do I always have to say a speaker name with the Bose Skill?","answer":"Yes. Alexa will not know where to direct your commands unless you include the speaker name in your requests/commands."},
{"id":81420,"deepfryd_id":"53808-0273","features":"even-keeled","question":"Does the Bose Skill let me play music on multiple speakers at the same time?","answer":"No. There is currently no way to play music on multiple speakers using just your voice with the Bose Skill. However, you can still create groups in the SoundTouch app as normal, even if the music was started through the Bose Skill."},
{"id":21,"deepfryd_id":"0268-1102","features":"Cross-platform","question":"support","answer":"grid-enabled"},
{"id":22,"deepfryd_id":"64117-305","features":"Grass-roots","question":"Balanced","answer":"fresh-thinking"},
{"id":23,"deepfryd_id":"41520-525","features":"approach","question":"ability","answer":"complexity"},
{"id":24,"deepfryd_id":"51672-4061","features":"Realigned","question":"concept","answer":"Diverse"},
{"id":25,"deepfryd_id":"62362-119","features":"Right-sized","question":"circuit","answer":"didactic"},
{"id":26,"deepfryd_id":"0591-2718","features":"success","question":"stable","answer":"alliance"},
{"id":27,"deepfryd_id":"50436-0913","features":"even-keeled","question":"value-added","answer":"mobile"},
{"id":28,"deepfryd_id":"0363-0345","features":"interface","question":"intranet","answer":"archive"},
{"id":29,"deepfryd_id":"57627-153","features":"reciprocal","question":"foreground","answer":"global"},
{"id":30,"deepfryd_id":"61703-344","features":"systematic","question":"grid-enabled","answer":"Centralized"},
{"id":31,"deepfryd_id":"54868-4073","features":"Networked","question":"Multi-layered","answer":"radical"},
{"id":32,"deepfryd_id":"52124-1023","features":"moderator","question":"protocol","answer":"intangible"},
{"id":33,"deepfryd_id":"64942-1190","features":"matrix","question":"Reverse-engineered","answer":"implementation"},
{"id":34,"deepfryd_id":"54868-5067","features":"Fully-configurable","question":"Synergistic","answer":"clear-thinking"},
{"id":35,"deepfryd_id":"50730-3001","features":"circuit","question":"mission-critical","answer":"archive"},
{"id":36,"deepfryd_id":"0941-0430","features":"middleware","question":"Assimilated","answer":"flexibility"},
{"id":37,"deepfryd_id":"14783-099","features":"methodology","question":"task-force","answer":"synergy"},
{"id":38,"deepfryd_id":"54569-0646","features":"monitoring","question":"neural-net","answer":"hardware"},
{"id":39,"deepfryd_id":"55891-002","features":"context-sensitive","question":"instruction set","answer":"Assimilated"},
{"id":40,"deepfryd_id":"52124-0114","features":"bifurcated","question":"mission-critical","answer":"zero defect"},
{"id":41,"deepfryd_id":"63323-496","features":"Re-contextualized","question":"Universal","answer":"Distributed"},
{"id":42,"deepfryd_id":"0268-0801","features":"disintermediate","question":"capacity","answer":"service-desk"},
{"id":43,"deepfryd_id":"44183-442","features":"executive","question":"static","answer":"multimedia"},
{"id":44,"deepfryd_id":"0270-5164","features":"Synchronised","question":"Secured","answer":"Right-sized"},
{"id":45,"deepfryd_id":"58232-0033","features":"responsive","question":"fresh-thinking","answer":"intermediate"},
{"id":46,"deepfryd_id":"41163-120","features":"strategy","question":"tertiary","answer":"function"},
{"id":47,"deepfryd_id":"63629-2655","features":"open system","question":"Diverse","answer":"object-oriented"},
{"id":48,"deepfryd_id":"46987-325","features":"Cloned","question":"Vision-oriented","answer":"Synchronised"},
{"id":49,"deepfryd_id":"54575-452","features":"flexibility","question":"archive","answer":"system-worthy"},
{"id":50,"deepfryd_id":"64117-127","features":"motivating","question":"methodology","answer":"interactive"},
{"id":51,"deepfryd_id":"50436-8000","features":"policy","question":"fresh-thinking","answer":"User-centric"},
{"id":52,"deepfryd_id":"65044-1860","features":"holistic","question":"encoding","answer":"instruction set"},
{"id":53,"deepfryd_id":"0555-9025","features":"leverage","question":"parallelism","answer":"fresh-thinking"},
{"id":54,"deepfryd_id":"52959-630","features":"Realigned","question":"motivating","answer":"Extended"},
{"id":55,"deepfryd_id":"0003-4214","features":"Distributed","question":"project","answer":"Balanced"},
{"id":56,"deepfryd_id":"51346-173","features":"neutral","question":"internet solution","answer":"task-force"},
{"id":57,"deepfryd_id":"64720-132","features":"directional","question":"Exclusive","answer":"Upgradable"},
{"id":58,"deepfryd_id":"49348-968","features":"stable","question":"core","answer":"object-oriented"},
{"id":59,"deepfryd_id":"37012-458","features":"Multi-layered","question":"Business-focused","answer":"Cross-platform"},
{"id":60,"deepfryd_id":"36987-3236","features":"Robust","question":"implementation","answer":"collaboration"},
{"id":61,"deepfryd_id":"0054-4650","features":"instruction set","question":"executive","answer":"info-mediaries"},
{"id":62,"deepfryd_id":"64679-661","features":"user-facing","question":"Cross-group","answer":"strategy"},
{"id":63,"deepfryd_id":"0904-6256","features":"discrete","question":"system engine","answer":"User-friendly"},
{"id":64,"deepfryd_id":"0178-0799","features":"directional","question":"systemic","answer":"software"},
{"id":65,"deepfryd_id":"0228-1113","features":"clear-thinking","question":"Devolved","answer":"Implemented"},
{"id":66,"deepfryd_id":"43498-250","features":"Cross-platform","question":"Virtual","answer":"algorithm"},
{"id":67,"deepfryd_id":"52862-003","features":"Exclusive","question":"Multi-tiered","answer":"Persevering"},
{"id":68,"deepfryd_id":"21695-997","features":"Face to face","question":"background","answer":"Profound"},
{"id":69,"deepfryd_id":"0172-2908","features":"analyzing","question":"Proactive","answer":"asymmetric"},
{"id":70,"deepfryd_id":"13537-500","features":"bifurcated","question":"product","answer":"Monitored"},
{"id":71,"deepfryd_id":"49230-197","features":"knowledge base","question":"client-server","answer":"software"},
{"id":72,"deepfryd_id":"19392-210","features":"Synchronised","question":"Persistent","answer":"focus group"},
{"id":73,"deepfryd_id":"64679-774","features":"algorithm","question":"Cross-platform","answer":"systemic"},
{"id":74,"deepfryd_id":"58232-0038","features":"real-time","question":"eco-centric","answer":"core"},
{"id":75,"deepfryd_id":"55154-6921","features":"utilisation","question":"Graphic Interface","answer":"optimizing"},
{"id":76,"deepfryd_id":"47682-080","features":"Integrated","question":"dedicated","answer":"Switchable"},
{"id":77,"deepfryd_id":"49884-685","features":"project","question":"benchmark","answer":"architecture"},
{"id":78,"deepfryd_id":"42549-570","features":"Multi-layered","question":"Organized","answer":"regional"},
{"id":79,"deepfryd_id":"55154-4607","features":"optimizing","question":"Polarised","answer":"eco-centric"},
{"id":80,"deepfryd_id":"46123-042","features":"global","question":"extranet","answer":"Persevering"},
{"id":81,"deepfryd_id":"68084-509","features":"modular","question":"Down-sized","answer":"contingency"},
{"id":82,"deepfryd_id":"0024-2791","features":"incremental","question":"bottom-line","answer":"intranet"},
{"id":83,"deepfryd_id":"61957-1112","features":"5th generation","question":"capability","answer":"circuit"},
{"id":84,"deepfryd_id":"65044-2098","features":"coherent","question":"Integrated","answer":"core"},
{"id":85,"deepfryd_id":"52584-003","features":"Progressive","question":"Assimilated","answer":"asymmetric"},
{"id":86,"deepfryd_id":"68306-108","features":"neural-net","question":"attitude","answer":"Pre-emptive"},
{"id":87,"deepfryd_id":"63187-027","features":"Reverse-engineered","question":"concept","answer":"protocol"},
{"id":88,"deepfryd_id":"50048-012","features":"Balanced","question":"Future-proofed","answer":"bi-directional"},
{"id":89,"deepfryd_id":"66116-403","features":"Programmable","question":"knowledge user","answer":"Object-based"},
{"id":90,"deepfryd_id":"31722-419","features":"productivity","question":"non-volatile","answer":"Compatible"},
{"id":91,"deepfryd_id":"42549-557","features":"info-mediaries","question":"Right-sized","answer":"Operative"},
{"id":92,"deepfryd_id":"55154-9615","features":"Upgradable","question":"web-enabled","answer":"value-added"},
{"id":93,"deepfryd_id":"59762-5014","features":"Stand-alone","question":"monitoring","answer":"encoding"},
{"id":94,"deepfryd_id":"56062-335","features":"orchestration","question":"Implemented","answer":"implementation"},
{"id":95,"deepfryd_id":"68788-9542","features":"Ameliorated","question":"product","answer":"knowledge base"},
{"id":96,"deepfryd_id":"50988-280","features":"task-force","question":"Polarised","answer":"pricing structure"},
{"id":97,"deepfryd_id":"33342-070","features":"didactic","question":"Open-architected","answer":"capability"},
{"id":98,"deepfryd_id":"10202-458","features":"attitude-oriented","question":"support","answer":"dedicated"},
{"id":99,"deepfryd_id":"10631-099","features":"pricing structure","question":"Team-oriented","answer":"policy"},
{"id":100,"deepfryd_id":"51079-129","features":"context-sensitive","question":"definition","answer":"client-driven"}];